default_stages: [commit, push]
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-yaml
    -   id: debug-statements
    -   id: check-merge-conflict
    -   id: detect-private-key
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: [--autofix]
-   repo: https://github.com/ambv/black
    rev: 23.1.0
    hooks:
    - id: black
      args: [--line-length=120]
      language_version: python3.11
