version: "3.7"

networks:
  protobox-gateway-network:
    driver: bridge

services:
  api:
    container_name: protobox-gateway-api
    image: protobox-gateway-api:0.1
    build:
      context: ./api
    networks:
      - protobox-gateway-network
    depends_on:
      - mongo
    restart: unless-stopped
    environment:
      - MONGODB_CONNECTION_STRING=${MONGODB_CONNECTION_STRING:-mongodb://localhost:27017/}
      - SWARM_SERVER_URL=${SWARM_SERVER_URL:-http://localhost:1633/}
  bee:
    image: ethersphere/bee:stable
    container_name: protobox-gateway-bee
    networks:
      - protobox-gateway-network
    volumes:
        - /home/bee/.bee:/home/bee/.bee
    ports:
      - "1633:1633"
      - "1634:1634"
      - "1635:1635"
    command:
      - "start"
  mongo:
    container_name: protobox-gateway-mongo
    image: mongo
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - protobox-gateway-network
    volumes:
      - /home/protobox-data/mongodb:/data/db
    restart: unless-stopped
