version: "3.7"

networks:
  protobox-network:
    external: true

services:
  api:
    container_name: protobox-gateway-api
    image: protobox-gateway-api:0.1
    build:
      context: ./api
    networks:
      - protobox-network
    restart: unless-stopped
    env_file:
      - .env
