version: "3.7"

networks:
  protobox-gateway-network:
    driver: bridge

services:
  api:
    container_name: protobox-gateway-api
    image: protobox-gateway-api:0.1
    build:
      context: ./api
    networks:
      - protobox-gateway-network
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: protobox-gateway-nginx
    networks:
      - protobox-gateway-network
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - /root/ssl/:/root/ssl/
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
