version: "3.7"

networks:
  protobox-network:
    driver: bridge

services:
  api:
    container_name: protobox-gateway-api
    image: protobox-gateway-api:0.1
    build:
      context: ./api
    networks:
      - protobox-network
    restart: unless-stopped
    env_file:
      - .env
  presto:
    image: prestodb/presto:latest
    container_name: presto
    networks:
      - protobox-network
    ports:
      - "8080:8080"
    volumes:
      - ./presto/mongodb.properties:/opt/presto-server/etc/catalog/mongodb.properties
  superset:
    build: ./superset
    container_name: superset
    networks:
      - protobox-network
    depends_on:
      - postgres
    ports:
      - "8088:8088"
    volumes:
      - ./superset/superset_config.py:/app/superset/superset_config.py
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset/superset_config.py
  postgres:
    image: postgres:16.1-alpine3.18
    container_name: postgres
    networks:
      - protobox-network
    volumes:
      - ./.postgres:/var/lib/postgresql
      - ./.postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=superset
      - POSTGRES_PASSWORD=superset
      - POSTGRES_DB=superset
